export const MOCK_EMAIL_SERVICE = "MOCK";
export const RESEND_EMAIL_SERVICE = "RESEND";
export const EMAIL_SERVICES = [
  MOCK_EMAIL_SERVICE,
  RESEND_EMAIL_SERVICE,
] as const;
export const MOCK_STORAGE_SERVICE = "MOCK";
export const GOOGLE_STORAGE_SERVICE = "GOOGLE";
export const STORAGE_SERVICES = [
  MOCK_STORAGE_SERVICE,
  GOOGLE_STORAGE_SERVICE,
] as const;
export const MOCK_CAPTCHA_SERVICE = "MOCK";
export const TURNSTILE_CAPTCHA_SERVICE = "TURNSTILE";
export const CAPTCHA_SERVICES = [
  MOCK_CAPTCHA_SERVICE,
  TURNSTILE_CAPTCHA_SERVICE,
] as const;
export const LIB_VALIDATION_SERVICE = "LIB";
