name: Cleanup Old Cloudflare Deployments

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allows manual triggering

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PAGES_PROJECT_WEBSITE }}

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          chmod +x ./scripts/cleanup-old-cloudflare-builds.sh

      - name: Run Cleanup Script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
        run: ./scripts/cleanup-old-cloudflare-builds.sh
