name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  deployments: write

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PAGES_PROJECT_WEBSITE }}

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        env:
          BRANCH: ${{ github.ref_name }}
          PR_NUMBER: "${{ github.event.pull_request.number }}"
        run: |
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          if [[ "$BRANCH" == "main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://staptis.com" >> $GITHUB_ENV

          elif [[ "$BRANCH" == "staging" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://${BRANCH}.${CLOUDFLARE_PROJECT_NAME}.pages.dev" >> $GITHUB_ENV

          elif [[ "$BRANCH" == "development" ]]; then
            echo "DEPLOY_ENV=development" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://${BRANCH}.${CLOUDFLARE_PROJECT_NAME}.pages.dev" >> $GITHUB_ENV

          elif [[ -n "$PR_NUMBER" ]]; then
            echo "DEPLOY_ENV=preview" >> $GITHUB_ENV
            echo "BRANCH=preview-${PR_NUMBER}" >> $GITHUB_ENV
            echo "DEPLOY_URL=https://preview-${PR_NUMBER}.${CLOUDFLARE_PROJECT_NAME}.pages.dev" >> $GITHUB_ENV
          fi
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install
      - name: Cache build artifacts (dist folder)
        uses: actions/cache@v3
        id: build_cache
        with:
          path: dist
          key: build-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('pnpm-lock.yaml', 'src/**/*', 'public/ **/*', 'functions/**/*', 'astro.config.mjs', 'wrangler.jsonc', 'tsconfig.json') }}
          restore-keys: ${{ runner.os }}-dist-website
      - if: steps.build_cache.outputs.cache-hit != 'true'
        env:
          PUBLIC_URL: ${{ env.DEPLOY_URL }}
        run: pnpm run build
      - name: start github deployment
        if: steps.build_cache.outputs.cache-hit != 'true'
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.DEPLOY_ENV }}
          env_url: ${{ env.DEPLOY_URL }}
          deployment_id: ${{ github.event.deployment.id }}
      - name: Deploy to Cloudflare Pages
        if: steps.build_cache.outputs.cache-hit != 'true'
        env:
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          pnpm dlx wrangler pages deploy ./dist \
            --project-name="$CLOUDFLARE_PROJECT_NAME" \
            --branch="$BRANCH" \
            --commit-hash="$COMMIT_HASH" \
            --commit-message="$COMMIT_MESSAGE"
      - name: Create GitHub Deployment
        if: steps.build_cache.outputs.cache-hit != 'true'
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.DEPLOY_ENV }}
          env_url: ${{ env.DEPLOY_URL }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  delete-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview deployment
        env:
          BRANCH: preview-${{ github.event.pull_request.number }}
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PROJECT_NAME/deployments?branch=$BRANCH" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json"
